# Generated by Django 4.2.3 on 2023-07-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('benifits', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealing.product')),
            ],
        ),
    ]
